### ISSUE TITLE
Webcheck - <urlopen error [Errno 10054] An existing connection was forcibly closed by the remote host>

### ISSUE THREAD

**Issue by Darxide23** [ssb22/web-imap-etc#1]
Like the title says. It ran fine for a while and now I get this whenever I run the script. The URL is still fine. I can get there through a browser with no issue.

**Comment by ssb22** [comment]
I've never seen this error before.  Can you share the URL (or email it to me privately if it's sensitive)?  Which platform are you on (OS, distro, version, Python version if you know it?)  Which version of webcheck? (if not latest, please try latest)  Thanks.

**Comment by Darxide23** [comment]
Windows 7 x64
Python 2.7.3
Webcheck v1.34
URL http://www.swagbucks.com/?cmd=gn-random-winner

I just updated to Python 2.7.15 and it works again. However, it worked fine with 2.7.3 for a day or two and then stopped working with that error. I will let you know if it happens again.

**Comment by ssb22** [comment]
Thanks. Turns out Error 10054 is Microsoft-speak for what we in the Unix world call "Connection reset by peer".  It usually means the server is treating us as a security threat and cutting our connection.  That could be because someone configured the server to reject our browser string (which can be changed), although I wouldn't have thought a Python upgrade would make any difference, unless perhaps the old version of Python has a bug that results in failure to use the browser string we ask for.  That server seems to be responding OK to most browser strings though.  It might just have been a temporary issue with the server; please reopen if it happens again.

Incidentally I know this is off-topic but that page looks like a scam to me; don't get caught out :-)
